# Site Settings
title: "Md Rufsan Jani Shanto"
name: "Md Rufsan Jani Shanto"
description: "Data/Business Analyst| Web Developer | AI/ML Researcher | Educator"
location: "Dhaka, Bangladesh"

# Site Author
author:
  name: "Md Rufsan Jani Shanto"
  avatar: "/images/profile.jpeg"
  bio: "Software Engineering Graduate (Major in Data Science) from DIU. Aspiring Researcher & Lecturer."
  location: "Dhaka, Bangladesh"
  github: "MdRufsan"
  linkedin: "https://www.linkedin.com/in/md-rufsan-jani-shanto-0408b732a/" # (এখানে আপনার আসল লিংকডইন ইউজারনেমটি বসাবেন)

